### ISSUE TITLE
Drupal core 10.1 への対応

### ISSUE THREAD

**Issue by bkenro** [bkenro/sqbase#6]
2022-12-6 に Drupal core 10.0.0 の rc2 がリリースされている。
https://www.drupal.org/project/drupal/releases/10.0.0-rc2

近くリリースされるであろう 10.0.0 の stable 版にコアをアップグレードした時の構成設定について検討する。

Drupal 10.0.0-rc3 への移行時にいったん削除したモジュール：

- [x] [Field Group Table](https://www.drupal.org/project/field_group_table)
- [x] [Webform](https://www.drupal.org/project/webform)
- [x] [Coffee](https://www.drupal.org/project/coffee)
- [x] [Back To Top](https://www.drupal.org/project/back_to_top)
- [x] ~~[jQuery UI Effect](https://www.drupal.org/project/jquery_ui_effects)~~（Back To Top からの依存関係がなくなり不要に）
- [x] [Insert](https://www.drupal.org/project/insert)
- [x] [Google Tag Manager](https://www.drupal.org/project/google_tag)
- [x] [AddToAny](https://www.drupal.org/project/addtoany)：チェック→[Automated Drupal 10 compatibility fixes](https://www.drupal.org/project/addtoany/issues/3296529#comment-14844088)
- [x] [CKEditor Color Button](https://www.drupal.org/project/colorbutton)
- [x] [Panel Button](https://www.drupal.org/project/panelbutton)
- [x] [CodeSnippet](https://www.drupal.org/project/codesnippet)

Drupal 10 対応しているが動作不安定：
- [x] [Block Class](https://www.drupal.org/project/block_class) ← [drupal_get_path() の呼び出し](https://www.drupal.org/project/block_class/issues/3323004)でブロックの設定画面が落ちる
- [x] [Easy Breadcrumb](https://www.drupal.org/project/easy_breadcrumb) ← [Wrong RouteObjectInterface for Drupal 10](https://www.drupal.org/project/easy_breadcrumb/issues/3323987) で落ちる

**Comment by bkenro** [comment]
まず、9.5-dev ブランチから分岐して 10.0-dev ブランチを作り、現時点で Drupal 10 に未対応のモジュールと、CKEditor5 に未対応のモジュールをいったん無効化して削除する。

Drupal 10 未対応モジュール：
- [Field Group Table](https://www.drupal.org/project/field_group_table)
- [Webform](https://www.drupal.org/project/webform)
- [Coffee](https://www.drupal.org/project/coffee)
- [Back To Top](https://www.drupal.org/project/back_to_top)
- [jQuery UI Effect](https://www.drupal.org/project/jquery_ui_effects)
- [Insert](https://www.drupal.org/project/insert)
- [Google Tag Manager](https://www.drupal.org/project/google_tag)
- [AddToAny](https://www.drupal.org/project/addtoany)

CKEditor5 未対応モジュール：
- [CKEditor Color Button](https://www.drupal.org/project/colorbutton)
- [Panel Button](https://www.drupal.org/project/panelbutton)
- [CodeSnippet](https://www.drupal.org/project/codesnippet)

その後、CKEditor のバージョンを 4 から 5 に移行する。

**Comment by bkenro** [comment]
現行の Devel 4.x と WebProfiler 9.x が D10 未対応のバージョンだった。構成設定の初期状態ではどちらも無効なので、削除して D10 移行後に再度インストールすることにする。

別のテスト環境で Easy Breadcrumb が正常に動作しないので、とりあえずこれも無効化して削除しておく。

composer.json には、デモ環境の都合で PHP 8.0 で動く条件を設定していたが、D10 では削除する。また、CKEditor 4 で使っていたプラグインの設定も削除しておく。

**Comment by bkenro** [comment]
この状態で SQbase プロファイルによるインストールを実行、正常に立ち上がることを確認。

```bash
$ drush @local site:install sqbase -y
```

**Comment by bkenro** [comment]
Field Group Table は D10 リリースがまだないが、
https://www.drupal.org/project/field_group_table

実装コードの修正は不要で info.yml の変更だけで対応できる模様：
https://www.drupal.org/project/field_group_table/issues/3287516
実際にパッチを適用してみたところ問題なく動作している。

**Comment by bkenro** [comment]
[CKEditor Color Button](https://www.drupal.org/project/colorbutton)、[Panel Button](https://www.drupal.org/project/panelbutton)、[CodeSnippet](https://www.drupal.org/project/codesnippet) は CKEditor 4 前提なので、CKEditor 5 移行とともに削除し、D10 では廃止とするか類似の機能を別途検討する。
[Insert](https://www.drupal.org/project/insert) も、メンテナが CKEditor 5 対応に消極的なので、D10 では代替手段を検討する。

**Comment by bkenro** [comment]
その後、Field Group Table も D10 に対応。CKEditor 4 関係と Insert の削除で D10 移行できる状況になったので、メインブランチを D10 に移行することにする。

下記を削除：
- bower-asset/dompurify
- ckeditor-plugin/colorbutton
- ckeditor-plugin/panelbutton
- drupal/insert

D10対応（推奨）バージョンへの移行：
- drupal/core-composer-scaffold: ^10
- drupal/core-project-message: ^10
- drupal/core-recommended: ^10
- drupal/devel: ^5.0
- drupal/metatag: ^2.0
- drupal/schema_metatag: ^3.0
- drupal/webprofiler: ^10.0
- drush/drush: ^12

その他：
- PHP 8.0 への制限を除去
- metatag_views をアンインストール（[2927551](https://www.drupal.org/project/metatag/issues/2927551) を回避するため）
- squtil をアンインストール（codesnippet の削除で不要に）

**Comment by bkenro** [comment]
下記コマンドでサイトをインストール出来ることを確認：
```
drush @local site:install sqbase
```

ただし、Drush 12 だとサイトエイリアスの root オプションがなぜか効かない。Drush 8 をランチャーに使っているせいかもしれないが、とりあえず、安定して動作する 11 にダウングレードした後、デモサイトに同期コピーして正常動作を確認：
https://sqbase.white-root.com/
